name: Makefile CI

on:
  push:
    branches:
    - main
    - develop
    - CI/CD
  pull_request:
    branches: [ "develop", "main", "CI/CD" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: make
