name: Clean and Build package

on:
  pull_request:
    branches: [ '**' ]

jobs:
  Build_in_package_dir:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: cd package && bazel clean --expunge && bazel build //... 
