name: Makefile CI

on:
  push:
    branches:
    - '**'
  pull_request:
    branches: [ '**' ]

jobs:
  Build_in_package_dir:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: cd package && make
